// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDip-DQ0d9L2ChQ_SF6IxJmDJTvYVq6hTI',
    appId: '1:922010564453:web:961f36285d35d86f99938c',
    messagingSenderId: '922010564453',
    projectId: 'pa-app-fa5b7',
    authDomain: 'pa-app-fa5b7.firebaseapp.com',
    storageBucket: 'pa-app-fa5b7.firebasestorage.app',
    measurementId: 'G-MB5SGJ9G47',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0QBYZlgpkCRcEx90N4yvGh-2EHm-0AyM',
    appId: '1:922010564453:android:6e1a5fa54190e90c99938c',
    messagingSenderId: '922010564453',
    projectId: 'pa-app-fa5b7',
    storageBucket: 'pa-app-fa5b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANDHv6eV-CR-vfm_vIdlG8CsGL-vxfxOE',
    appId: '1:922010564453:ios:386072d36da5332299938c',
    messagingSenderId: '922010564453',
    projectId: 'pa-app-fa5b7',
    storageBucket: 'pa-app-fa5b7.firebasestorage.app',
    iosBundleId: 'com.example.humdamSoulsync',
  );
}
